### ISSUE TITLE
option -e  and -s/-m 

### ISSUE THREAD

**Issue by servidge** [tenox7/ttyplot#40] opened 2019-07-12 23:22 UTC
It seems the options does not work properly. please correct me if i am wrong. 
- If the option -e is used there is only the Usage output so the preferred exceed character doesn't work. 
- If the option -m is used the -s option seems to be ignored. The graph limit at start is the given -m input. From my understanding the -s should be the first limit for the graph. If this is exceeded the last limit is the -m limit and the -e character is used to visualise this exception.

The tested version is compiled from today's source. 1.4

PS: despite that a cool piece of software ;)

**Comment by tenox7** [comment] 2019-07-24 23:54
You are absolutely right about `-e` not being honored right now. It's a bug. It was missing in _optstring_. Fixed now.

You are also right about `-s` not being used when -m is specified. However this is by design. Think of flag `-s` is not a limit of any kind. It's an initial or minimal graph or scale height. Most commonly used when for  measuring something that has a known scale like CPU usage in % (the top being 100%) or link bandwidth (the top being xxx MB/s). You use `-s` when you don't want an actual limit but you want graph to be scaled minimally at x value. You use `-m` when you want a completely fixed scale never to go lover or higher than the value of the flag. One can think that `-m` is inclusive of `-s` and therefore specifying `-s` has no effect. Let me know if I can word it better way in help/description/usage.

**Comment by tenox7** [comment] 2019-07-25 00:03
I have updated the usage regarding `-s` and `-m` to be less confusing:
```
  -s minimum/initial scale of the plot (can go above if data input has larger value)
  -m maximum value, if exceeded draws error line (see -e), plot scale is fixed
```

**Closed** 2019-07-25 00:15 UTC

**Comment by tenox7** [comment] 2019-07-25 00:18
fixed in head:master

**Comment by servidge** [comment] 2019-07-26 22:39
Ok, i can confirm the fix. 
And the -s or -m parameters are used either or and not both at the same time. If you use the -s the -e does not take effect. i can live with that. 
thanks for the fix

**Comment by tenox7** [comment] 2019-07-30 08:01
if -m is used -s becomes redundant, also if -s (and not -m) then -e is never used, so... yes :)
